### ISSUE TITLE
[INFO] Alternative way of keeloq cloning

### ISSUE THREAD

**Issue by iDoka** [DerBunker/keygate#1]
Inspired by your work I describe advanced way to cloning: http://idoka.ru/blog/posts/keeloq-protocol-simple-cloning/

I'll appreciate to adding alternative approach to README.md

**Comment by DerBunker** [comment]
Hi) We've added your method to readme. Thanks for your interest. In fact it requires a little more work (we choose much easier way), but it's awesome :)
